version: "3"
services:
  app:
    env_file:
      - .env
    environment:
      - ROCKET_TEMPLATES_DIR=/app/templates
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
